[package]
name = "fluid_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.7.0"
random = "0.12.2"
glam = { version = "0.21.2", features = ["mint"] }
